.editorconfig
.gitignore
LICENSE.md
js/modules/.gitkeep
package.json

Constructed initial folder structure that will be enough for the first phase of the project.
`css/modules` folder will be where all modular CSS files should be stored, all modules will be bundled in the main `framework.css` file.
Same should be enough for javascript files too, in their own `js/modules` and `framework.js` files.
`docs` should be place where all documentation for the project should be stored.
`.gitignore` and `.editorconf` files should be there to stop unwanted files from pushing to repo, and to enforce code styles between different editors and IDEs.

Add initial folder structure

---

Team.md

Would be a good idea to create a development branch for people to work on before merging into master.

Updated team list

---

Team.md

signed myself into the Team.md

updated Team

---

Team.md

Team reorganized

---

README.md

i tried to use git stuff via pulling that missing word

missing word at markters ---> marketers

---

src/assets/scss/style.scss

Using mixin. Defining the no. of columns and margin between them

Making any grid size

---

t-basic.scss

Add t-basic section to t-basic.scss

---

t-basic.scss

I am done with the task and sorry for  the delay

 Integrating the basic article style

---

src/test-template.html

testing the framework in html

---

src/test-template-1.html

https://codepen.io/yigitserdar/pen/vppVoN

Test tamplate html #81

---

src/scss/themes/t-news.scss

I've added code for NEWS template header, nav and footer. It's my first pull request for this repo, I hope I've done all as I should have :)
Preview here: https://codepen.io/AniaM/pen/PERqxw

Adds nav, header, footer to t-news template

---

src/scss/styles.scss

add grid columns classes for:
3 columns 20%-60%-20% using "fr" units without and with gap
2 columns 70%-30% using "fr" units without and with gap
4 columns 10%-40%-40%-10% using "fr" units without and with gap

Add grid columns classes

---

src/scss/styles.scss

Create CSS Grid columns - 3 columns (20% / 40% / 40%) using "fr" unit

added 3 columns (20% / 40% / 40%) using "fr" unit

---

.gitignore
src/scss/styles.scss

Hey, hope this matches up ok. Also added /dist folder to .gitignore for future versions.

Added CSS rows

---

src/scss/themes/t-2.scss

Hi, this is issue#140 solution.

issue#140 solution

---

src/scss/styles.scss

Hello, I added CSS classes to create Grid 07, as per instructions of issue #147.

Issue #147

---

src/scss/themes/t-blue.scss

Hi Maeva, this is for the section #125 thank you

#125 Integrate the SECTION to the template BLUE

---

src/scss/themes/t-blue.scss

Hi Maeva, if it is something I forgot to add please tell me and I'll add it. thanks

#128 Integrate the FOOTER to the template BLUE

---

website/src/about.html
website/src/documentation.html
website/src/index.html

I have replaced the font awesome with paths to svg icons from the repo

Added paths to svg images instead of font awesome

---

website/src/about.html
website/src/documentation.html
website/src/index.html

Replaced ulight logo svg with png on headers

---

website/src/about.html

I have added a footer section according to CodePen proposal. 
https://codepen.io/eaczechova/pen/YezYNO?editors=1100

Add footer

---

website/src/about.html
website/src/assets/css/style.css

Fix: responsive issues in about.html view.

About us view

---

src/scss/themes/t-orange.scss

t-orange.scss

---

src/scss/themes/t-orange.html

t-orange.html
